### ISSUE TITLE
Proposal/Feature request: Add IPv6 support.

### ISSUE THREAD

**Issue by spikebike** [nictuku/dht#29]
One of the harder parts of P2P is dealing with IP Masq/NAT'd peers.  Fortunately there's an awesome fix, IPv6.  Google claims 9.85% of Google's traffic in the USA is from IPv6 users, far from a trivial number.  I've managed to get IPv6 connectivity working at 2 locations so I can tinker.  Comcast is giving out /60's to regular home users!

I'm going to take a shot at it.  I've not written any IPv6 code before though.  

The resources I'm referencing are https://github.com/jech/dht and http://www.bittorrent.org/beps/bep_0032.html.

Just figured I'd post here in case anyone else is interested or planning similar.

**Comment by spikebike** [comment]
Tweaked pull request with feedback from nictuku.

**Comment by nictuku** [comment]
Should we consider this closed? :)

**Comment by spikebike** [comment]
One piece of functionality is missing is the BEP described ability to query IPv4 peers for new IPv6 peers and vice versa.  Seems to only be a bootstrapping issue.  It's on the todo list, but not sure which approach would be best.  

But yeah, I consider this closed.
