### ISSUE TITLE
Project has moved

### ISSUE THREAD

**Issue by hyg** [nictuku/dht#34]
code.google.com/p/bencode-go  ==> github.com/jackpal/bencode-go
code.google.com/p/vitess/go/cache  ==> github.com/youtube/vitess/go/cache

**Comment by nictuku** [comment]
Fixed by https://github.com/nictuku/dht/commit/e001f2d9f632af646462f6d90a40d6f4cfc528da

**Comment by nictuku** [comment]
Also moved vitess from nettools:
https://github.com/nictuku/nettools/commit/d20cc556b90a2470bb2c7e3cb7efaa0f6fbf7633
