### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by pierrre** [nictuku/dht#36]
In your project, you use `github.com/youtube/vitess/go/cache` and `github.com/golang/groupcache/lru`.
These dependencies are HUGE and you only need a small part.
You should copy them and create a small repository, like https://github.com/pierrre/lrucache .

**Comment by spikebike** [comment]
(I'm not nicktuku obviously, this is just my opinion)

Can you provide a file and line number for github.com/youtube/vitess/go/cache?  I didn't see it.

Groupcache is 1900 lines of code or so in 16 files, to copy them and create a small repository would be a substantial burden to track any future improvements, bugfixes, and related.  Not to mention time to remove the uneeded pieces.  It should take any reasonable machine just a few seconds to download and compile it, it's under 1MB.  It happens automatically if you use the standard go tools.

What is the downside of using groupcache that would justify forking and maintaining a seperate tree?  

Seems like programmer hours could be spent elsewhere.

**Comment by pierrre** [comment]
Groupcache is only used here: https://github.com/nictuku/dht/blob/master/peer_store.go
And only the subpackage `github.com/golang/groupcache/lru` is used.
This package is small: https://github.com/golang/groupcache/tree/master/lru
It doesn't change often.

Vitess is only used here: https://github.com/nictuku/nettools/blob/master/ratelimit.go (its a dependency)
And only the subpackage `github.com/youtube/vitess/go/cache` is used.
This package is small too: https://github.com/youtube/vitess/tree/master/go/cache


In my project https://github.com/pierrre/imageserver/blob/master/cache/memory/memory.go
I need an LRU cache.
The package from vitess was perfect, but I didn't want to import all the vitess project.
That's why I created this repository: https://github.com/pierrre/lrucache

**Comment by nictuku** [comment]
What's the practical problem with using those dependencies? If you explain what kind of issues that's bringing to you, I'd consider options. So far, you're just saying "they are big" but not making it clear what kind of problems it's bringing.

**Comment by nictuku** [comment]
@pierrre please do feel free to re-open this if you have other more compelling reasons for changing our dependencies.
